### ISSUE TITLE
cannot import Pannellum

### ISSUE THREAD

**Issue by dingdingbai** [spybaby1/360-react-pannellum#2]
Hi，thanks for this repository, but while building with Webpack, I'm getting this error:

![image](https://user-images.githubusercontent.com/19373581/31811710-2670db6c-b546-11e7-80de-623e681beb84.png)
 
Here is my code:
import Pannellum from '360-react-pannellum/lib/index'

**Comment by spybaby1** [comment]
You can use
```
import { Pannellum } from '360-react-pannellum'
```

Sorry for my incorrect example

**Comment by bai1024** [comment]
Thank you~ 👏
